// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GameState_Add_ClickCount_ClickValue_ValuePerSecond : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameState_Add_ClickCount_ClickValue_ValuePerSecond));
        
        string IMigrationMetadata.Id
        {
            get { return "201703231201545_GameState_Add_ClickCount_ClickValue_ValuePerSecond"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
