// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GameStateAchievements_AchievementSuccess_Delete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameStateAchievements_AchievementSuccess_Delete));
        
        string IMigrationMetadata.Id
        {
            get { return "201703271015307_GameStateAchievements_AchievementSuccess_Delete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
